### PR TITLE
Add all android architectures and 32bit pc architectures to actions build

### PR DESCRIPTION
**Pull request by JezSonic**
- [x] Add all supported android architectures to the build
- [x] Add 32bit pc (on supported systems) architectures to the build
- [x] Attach fmod libs on PC and iOS builds
- [x] Update fmod API to newest available

### CODE REVIEW

**Comment by JezSonic** [comment]
Ok, now i have added another action, that also includes libs included in fmod. I did this for myself

**Comment by JezSonic** [comment]
ok, so it seems, i dont'know fmod file names on other platforms than linux :/

**Comment by JezSonic** [comment]
So i have fixed paths and this finally works. Also i have added iOS for compiling with fmod prebuild libs from fmod api
The hardest thing to do was get libs where are fmod prebuild libs placed in fmod api installation folders, but... i finally did it
🎉

**Comment by JezSonic** [comment]
So, i have updaed fmod api used here, to newest avaliable, to avoid fmod version errors

**Comment by 2shady4u** [comment]
🤔  The builds for this seem to be failing on Github Actions, are you sure this works?

**Comment by JezSonic** [comment]
Yes. Check https://github.com/NewDEV-github/fmod-gdnative/actions and see that this works

**Comment by 2shady4u** [comment]
Hello @JezSonic  could you squash your commits?
Currently there's like 20 commits in your branch which is a bit overkill to potentially merge :)

**Comment by JezSonic** [comment]
> Hello @JezSonic could you squash your commits?
> Currently there's like 20 commits in your branch which is a bit overkill to potentially merge :)

I kinda don't know how to do this :/

**Pull request closed without merging**
